"use client";
import { useEffect, useMemo, useState } from "react";

type Holding={id:string;market:string;symbol:string;quantity:string;average_cost:string;currency:string;enabled:boolean};
type Watch={id:string;market:string;symbol:string;enabled:boolean;upper_percent:string|null;lower_percent:string|null};
type Alert={id:string;market:string;symbol:string;alert_type:string;change_percent:string|null;status:string;triggered_at:string;delivered_at:string|null;retry_count:number;last_error:string|null};
type Setting={key:string;value:unknown};
type Quote={market:string;symbol:string;price:string;currency:string;change_percent:string|null;source:string;quoted_at:string;stale:boolean};
type Summary={rows:{id:string;market:string;symbol:string;currency:string;cost_basis:number;current_value:number|null;pnl:number|null;pnl_percent:number|null;stale:boolean}[];totals:Record<string,{cost_basis:number;current_value:number;pnl:number}>};
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
const NAV:{[k:string]:string}={dashboard:"Dashboard",portfolio:"Portfolio",watchlist:"Watchlist",alerts:"Alert History",settings:"Settings"};
const pct=(v:number|null|string)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;
const money=(v:number|null,c="")=>v==null?"—":`${c} ${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function Home(){
 const[page,setPage]=useState("dashboard"),[holdings,setHoldings]=useState<Holding[]>([]),[watch,setWatch]=useState<Watch[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[settings,setSettings]=useState<Setting[]>([]),[quotes,setQuotes]=useState<Quote[]>([]),[summary,setSummary]=useState<Summary|null>(null),[system,setSystem]=useState<any>(null),[market,setMarket]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const paths=["portfolio","watchlist","alerts/history","settings","market/quotes","portfolio/summary","system/status","market/status"];const rs=await Promise.all(paths.map(x=>fetch(`${API}/api/v1/${x}`)));if(rs.some(x=>!x.ok))throw Error("API");const data=await Promise.all(rs.map(x=>x.json()));setHoldings(data[0]);setWatch(data[1]);setAlerts(data[2]);setSettings(data[3]);setQuotes(data[4]);setSummary(data[5]);setSystem(data[6]);setMarket(data[7])}catch{setError("เชื่อมต่อ API ไม่สำเร็จ")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const nav=Object.entries(NAV);
 return <div className="ms-shell"><aside className="ms-sidebar"><div className="ms-brand"><div className="ms-brand-mark">MS</div><div><strong>MyStockAlert</strong><small>Portfolio Monitor</small></div></div><nav>{nav.map(([k,v])=><button key={k} className={page===k?"ms-nav ms-nav-active":"ms-nav"} onClick={()=>setPage(k)}>{v}</button>)}</nav><div className="ms-sidebar-footer"><span className={system?.database?"ms-dot":"ms-dot ms-dot-off"}/> {system?.database?"API / DB OK":"Checking..."}</div></aside>
 <main className="ms-main"><header className="ms-header"><div><h1>{NAV[page]}</h1><p>Stock Portfolio & Alert System</p></div><button className="ms-button ms-button-light" onClick={load}>↻ Refresh</button></header>{error&&<div className="ms-banner ms-banner-error">{error}</div>}{loading?<div className="ms-card ms-card-body">กำลังโหลดข้อมูล...</div>:page==="dashboard"?<Dashboard h={holdings} w={watch} a={alerts} s={summary} m={market}/>:page==="portfolio"?<Portfolio rows={holdings} reload={load}/>:page==="watchlist"?<Watchlist rows={watch} reload={load}/>:page==="alerts"?<Alerts rows={alerts}/>:<Settings rows={settings} reload={load} system={system}/>}</main></div>
}

function Card({label,value,sub}:{label:string;value:string;sub?:string}){return <article className="ms-card ms-card-body"><div className="ms-label">{label}</div><div className="ms-stat-value">{value}</div>{sub&&<div className="ms-section-subtitle">{sub}</div>}</article>}
function Dashboard({h,w,a,s,m}:{h:Holding[];w:Watch[];a:Alert[];s:Summary|null;m:any[]}){
 const th=s?.totals.THB,us=s?.totals.USD;
 return <><section className="ms-grid ms-grid-4"><Card label="Holdings" value={String(h.length)}/><Card label="TH Portfolio" value={money(th?.current_value??0,"THB")} sub={pct(th?.pnl?th.pnl/(th.cost_basis||1)*100:null)}/><Card label="US Portfolio" value={money(us?.current_value??0,"USD")} sub={pct(us?.pnl?us.pnl/(us.cost_basis||1)*100:null)}/><Card label="Alerts" value={String(a.length)} sub={`${w.length} watchlist`}/></section><section className="ms-grid ms-grid-2 ms-dashboard-gap"><div className="ms-card"><div className="ms-card-header"><h2 className="ms-section-title">Portfolio P/L</h2></div><SummaryTable s={s}/></div><div className="ms-card"><div className="ms-card-header"><h2 className="ms-section-title">Market Status</h2></div><div className="ms-status-grid">{m.map(x=><div className="ms-status-row" key={x.market}><strong>{x.market}</strong><span className={x.open?"ms-badge-positive":"ms-badge-neutral"}>{x.open?"OPEN":"CLOSED"}</span><small>{x.timezone}</small></div>)}</div></div></section></>
}
function SummaryTable({s}:{s:Summary|null}){if(!s)return <Empty text="ยังไม่มีข้อมูล Portfolio"/>;return <div className="ms-table-wrap"><table className="ms-table"><thead><tr><th>Currency</th><th>Cost</th><th>Value</th><th>P/L</th></tr></thead><tbody>{Object.entries(s.totals).map(([c,v])=><tr key={c}><td><strong>{c}</strong></td><td>{money(v.cost_basis,c)}</td><td>{money(v.current_value,c)}</td><td className={v.pnl>=0?"ms-positive":"ms-negative"}>{money(v.pnl,c)}</td></tr>)}</tbody></table></div>}
function Empty({text}:{text:string}){return <div className="ms-empty">{text}</div>}
function Form({children}:{children:React.ReactNode}){return <div className="ms-form-row">{children}</div>}
function Portfolio({rows,reload}:{rows:Holding[];reload:()=>void}){
 const empty={market:"TH",symbol:"",quantity:"",average_cost:"",currency:"THB",enabled:true}; const[f,setF]=useState<any>(empty); const[edit,setEdit]=useState<string|null>(null);
 async function save(){const method=edit?"PUT":"POST";const url=edit?`${API}/api/v1/portfolio/${edit}`:`${API}/api/v1/portfolio`;const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({...f,quantity:Number(f.quantity),average_cost:Number(f.average_cost)})});if(!r.ok)return alert("บันทึก Portfolio ไม่สำเร็จ");setF(empty);setEdit(null);reload()}
 async function remove(id:string){if(!confirm("ลบรายการนี้หรือไม่?"))return;const r=await fetch(`${API}/api/v1/portfolio/${id}`,{method:"DELETE"});if(r.ok)reload()}
 return <section className="ms-card"><div className="ms-card-header"><div><h2 className="ms-section-title">{edit?"Edit Holding":"Add Holding"}</h2><p className="ms-section-subtitle">แก้ไข / ลบ / เปิด-ปิดรายการได้จากตาราง</p></div></div><Form><select value={f.market} onChange={e=>setF({...f,market:e.target.value,currency:e.target.value==="TH"?"THB":"USD"})}><option>TH</option><option>US</option></select><input placeholder="Symbol" value={f.symbol} onChange={e=>setF({...f,symbol:e.target.value.toUpperCase()})}/><input placeholder="Quantity" type="number" min="0" value={f.quantity} onChange={e=>setF({...f,quantity:e.target.value})}/><input placeholder="Average Cost" type="number" min="0" value={f.average_cost} onChange={e=>setF({...f,average_cost:e.target.value})}/><button className="ms-button" onClick={save}>{edit?"Save":"Add"}</button></Form>{edit&&<button className="ms-button ms-button-light ms-cancel" onClick={()=>{setEdit(null);setF(empty)}}>Cancel</button>}<div className="ms-table-wrap"><table className="ms-table"><thead><tr><th>Market</th><th>Symbol</th><th>Qty</th><th>Avg</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.market}</td><td><strong>{x.symbol}</strong></td><td>{x.quantity}</td><td>{x.average_cost} {x.currency}</td><td><button className="ms-link" onClick={()=>{setEdit(x.id);setF({...x,quantity:String(x.quantity),average_cost:String(x.average_cost)})}}>Edit</button><button className="ms-link ms-danger" onClick={()=>remove(x.id)}>Delete</button></td></tr>)}</tbody></table>{!rows.length&&<Empty text="ยังไม่มีหุ้นใน Portfolio"/>}</div></section>
}

function Watchlist({rows,reload}:{rows:Watch[];reload:()=>void}){
 const empty={market:"TH",symbol:"",upper_percent:"",lower_percent:"",enabled:true};const[f,setF]=useState<any>(empty);const[edit,setEdit]=useState<string|null>(null);
 async function save(){const method=edit?"PUT":"POST";const url=edit?`${API}/api/v1/watchlist/${edit}`:`${API}/api/v1/watchlist`;const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({...f,upper_percent:f.upper_percent===""?null:Number(f.upper_percent),lower_percent:f.lower_percent===""?null:Number(f.lower_percent)})});if(!r.ok)return alert("บันทึก Watchlist ไม่สำเร็จ");setF(empty);setEdit(null);reload()}
 async function remove(id:string){if(!confirm("ลบ Watchlist นี้หรือไม่?"))return;const r=await fetch(`${API}/api/v1/watchlist/${id}`,{method:"DELETE"});if(r.ok)reload()}
 return <section className="ms-card"><div className="ms-card-header"><div><h2 className="ms-section-title">{edit?"Edit Watchlist":"Add Watchlist"}</h2><p className="ms-section-subtitle">Upper ต้องเป็นบวก / Lower ต้องเป็นลบ</p></div></div><Form><select value={f.market} onChange={e=>setF({...f,market:e.target.value})}><option>TH</option><option>US</option></select><input placeholder="Symbol" value={f.symbol} onChange={e=>setF({...f,symbol:e.target.value.toUpperCase()})}/><input placeholder="Upper %" type="number" min="0" value={f.upper_percent} onChange={e=>setF({...f,upper_percent:e.target.value})}/><input placeholder="Lower %" type="number" max="0" value={f.lower_percent} onChange={e=>setF({...f,lower_percent:e.target.value})}/><button className="ms-button" onClick={save}>{edit?"Save":"Add"}</button></Form><div className="ms-table-wrap"><table className="ms-table"><thead><tr><th>Market</th><th>Symbol</th><th>Upper</th><th>Lower</th><th>State</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.market}</td><td><strong>{x.symbol}</strong></td><td className="ms-positive">{pct(x.upper_percent)}</td><td className="ms-negative">{pct(x.lower_percent)}</td><td>{x.enabled?"Enabled":"Disabled"}</td><td><button className="ms-link" onClick={()=>{setEdit(x.id);setF({...x,upper_percent:x.upper_percent||"",lower_percent:x.lower_percent||""})}}>Edit</button><button className="ms-link ms-danger" onClick={()=>remove(x.id)}>Delete</button></td></tr>)}</tbody></table>{!rows.length&&<Empty text="ยังไม่มี Watchlist"/>}</div></section>
}
function Alerts({rows}:{rows:Alert[]}){return <section className="ms-card"><div className="ms-card-header"><div><h2 className="ms-section-title">Alert History</h2><p className="ms-section-subtitle">Triggered ≠ delivered: LINE delivery is queued separately</p></div></div><div className="ms-table-wrap"><table className="ms-table"><thead><tr><th>Triggered</th><th>Market</th><th>Symbol</th><th>Type</th><th>Change</th><th>Status</th><th>Retries</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{new Date(x.triggered_at).toLocaleString("th-TH")}</td><td>{x.market}</td><td><strong>{x.symbol}</strong></td><td>{x.alert_type}</td><td className={Number(x.change_percent)>=0?"ms-positive":"ms-negative"}>{pct(x.change_percent)}</td><td><span className={x.status==="delivered"?"ms-badge-positive":"ms-badge-neutral"}>{x.status}</span></td><td>{x.retry_count}{x.last_error&&<small className="ms-error-text"> · {x.last_error}</small>}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="ยังไม่มีประวัติการแจ้งเตือน"/>}</div></section>}

function Settings({rows,reload,system}:{rows:Setting[];reload:()=>void;system:any}){
 const defaults={refresh_interval:30,notifications_enabled:true,alert_on_open:true,alert_on_close:true,display_currency:"native",fx_usd_thb:35};const merged:any={...defaults};rows.forEach(x=>merged[x.key]=x.value);
 async function save(key:string,value:any){const r=await fetch(`${API}/api/v1/settings/${key}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({value})});if(!r.ok)alert("บันทึกไม่สำเร็จ");else reload()}
 const toggle=(key:string)=><label className="ms-setting"><span>{key}</span><input type="checkbox" checked={Boolean(merged[key])} onChange={e=>save(key,e.target.checked)}/></label>;
 return <section className="ms-grid ms-grid-2"><div className="ms-card ms-card-body"><h2 className="ms-section-title">Typed Settings</h2><p className="ms-section-subtitle">ตั้งค่าที่ระบบใช้จริง</p><label className="ms-setting-block">Refresh interval (sec)<input type="number" min="10" value={merged.refresh_interval} onChange={e=>save("refresh_interval",Number(e.target.value))}/></label>{toggle("notifications_enabled")}{toggle("alert_on_open")}{toggle("alert_on_close")}<label className="ms-setting-block">Display currency<select value={merged.display_currency} onChange={e=>save("display_currency",e.target.value)}><option value="native">Native THB / USD</option><option value="THB">THB</option><option value="USD">USD</option></select></label><label className="ms-setting-block">USD/THB FX<input type="number" min="0" value={merged.fx_usd_thb} onChange={e=>save("fx_usd_thb",Number(e.target.value))}/></label></div><div className="ms-card ms-card-body"><h2 className="ms-section-title">System Status</h2><div className="ms-status-grid"><div className="ms-status-row"><strong>Database</strong><span className="ms-badge-positive">{system?.database?"OK":"DOWN"}</span></div><div className="ms-status-row"><strong>Quote Cache</strong><span>{system?.quote_cache??0} rows</span></div><div className="ms-status-row"><strong>Pending Delivery</strong><span>{system?.pending_deliveries??0}</span></div><div className="ms-status-row"><strong>Version</strong><span>{system?.version||"—"}</span></div></div></div></section>
}
