from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table("users", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")), sa.Column("username", sa.String(100), nullable=False, unique=True), sa.Column("password_hash", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("portfolio_holdings", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("market", sa.String(10), nullable=False), sa.Column("symbol", sa.String(32), nullable=False), sa.Column("quantity", sa.Numeric(20,8), nullable=False), sa.Column("average_cost", sa.Numeric(20,8), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("enabled", sa.Boolean(), server_default=sa.true(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("watchlist_items", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("market", sa.String(10), nullable=False), sa.Column("symbol", sa.String(32), nullable=False), sa.Column("enabled", sa.Boolean(), server_default=sa.true(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("user_id","market","symbol"))
    op.create_table("alert_rules", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")), sa.Column("watchlist_item_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("watchlist_items.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("upper_percent", sa.Numeric(10,4)), sa.Column("lower_percent", sa.Numeric(10,4)), sa.Column("enabled", sa.Boolean(), server_default=sa.true(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("alert_history", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("symbol", sa.String(32), nullable=False), sa.Column("market", sa.String(10), nullable=False), sa.Column("alert_type", sa.String(64), nullable=False), sa.Column("reference_price", sa.Numeric(20,8)), sa.Column("trigger_price", sa.Numeric(20,8)), sa.Column("change_percent", sa.Numeric(12,6)), sa.Column("message", sa.Text()), sa.Column("sent_at", sa.DateTime(timezone=True)), sa.Column("status", sa.String(32), server_default="pending", nullable=False))
    op.create_table("market_sessions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")), sa.Column("market", sa.String(10), nullable=False), sa.Column("session_date", sa.Date(), nullable=False), sa.Column("timezone", sa.String(64), nullable=False), sa.Column("open_at", sa.DateTime(timezone=True)), sa.Column("close_at", sa.DateTime(timezone=True)), sa.Column("is_trading_day", sa.Boolean(), server_default=sa.true(), nullable=False), sa.UniqueConstraint("market","session_date"))
    op.create_table("settings", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("key", sa.String(100), nullable=False), sa.Column("value_encrypted_or_json", postgresql.JSONB()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("user_id","key"))
    op.execute("INSERT INTO users (username, password_hash) VALUES ('demo', 'phase1-placeholder') ON CONFLICT (username) DO NOTHING")

def downgrade():
    for table in ("settings","market_sessions","alert_history","alert_rules","watchlist_items","portfolio_holdings","users"):
        op.drop_table(table)
